[package]
name = "snake-game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "snake_game"
path = "src/libraries/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"
